- views/layout.html
- views/static/about.html
另外增加了meta apple-itunes-app， 提示iOS用户有客户端。
meta文档： https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
> 在关于页面增加了移动客户端的相关信息

- public/stylesheets/style.less
- views/reply/reply.html
1. show user avatar and name together.
2. make reply action icons larger so easy to click
3. remove image width and height attr as have been defined in user_avatar css.
> fix issue #479

- controllers/site.js
- public/stylesheets/style.less
- views/sidebar.html
- views/static/about.html
- web_router.js
> 在页面右侧增加客户端下载二维码

- api/v1/topic.js
- api/v1/user.js
- api_router_v1.js
- test/api/v1/topic.test.js
- views/static/api.html
* [新增] post /topic/collect 收藏主题
* [新增] post /topic/de_collect 取消收藏
* [修改] get /user/:loginname 用户详情
* 增加collect_topics 用户已收藏的主题
获取已收藏主题也可以单做一个接口，不放在user里面
@alsotang 你脚的呢
> 增加主题收藏的相关接口

- README.md
- public/libs/editor/editor.css
解决issue #495 cannot find module './config' solution
> fix issue #495

- config.default.js
- controllers/message.js
- proxy/message.js
- proxy/reply.js
- proxy/topic.js
修正 getTopicsByQuery 的查询，避免多条的 Topic find by id 对数据库带来多余的开销；
> Improve db query

- README.md
- app.js
1. README.md 里面的运行环境由 `Node.js` 改成了`io.js`;
2. app.js 里面的`%d`由于common/log.js不是调用的console.log而不起作用，删除了 `%d`;
> README 线上运行环境 Node.js -> io.js

- views/sidebar.html
> 删除CN-IOJS的链接

- README.md
codecov.io seems do not provide a custom style, so use the badge on http://shields.io
> Badge: use flat-square style for codecov

- public/stylesheets/style.less
- views/topic/index.html
#815 
微信测试没有问题。使用方式就是点击喽~~
打开之后，再次点击关闭。
具体截图如下：
> 我用一个 bs 的 modal 实现了图片预览，作为参考

- public/stylesheets/style.less
- views/topic/index.html
这次关闭之后，能恢复页面的滚动能力了。
顺便在图片上加了一些特技，来标识这个图片可以点击查看。
如果觉得不喜欢，我就删掉好了
> 修复了一个预览消失后无法恢复 Body 滚动权的 Bug，顺便加了一发特技~~

- api/v1/message.js
- api/v1/middleware.js
- api/v1/reply.js
- api/v1/tools.js
- api/v1/topic.js
- api/v1/topic_collect.js
- api/v1/user.js
- test/api/v1/tools.test.js
https://github.com/cnodejs/nodeclub/issues/819
> 修复API的http状态码，错误消息改成中文提示，方便前段直接显示错误提示

- api/v1/reply.js
- api/v1/topic_collect.js
- test/api/v1/message.test.js
- test/api/v1/reply.test.js
- test/api/v1/tools.test.js
- test/api/v1/topic.test.js
- test/api/v1/topic_collect.test.js
- test/api/v1/user.test.js
> 修复部分API接口有可能出现500的问题，补充API接口的测试用例

- api/v1/reply.js
- api/v1/topic.js
- api/v1/topic_collect.js
- test/api/v1/reply.test.js
- test/api/v1/topic.test.js
- test/api/v1/topic_collect.test.js
https://github.com/cnodejs/nodeclub/issues/830
> 修改API接口中参数错误的http状态吗 422 -> 400

- api/v1/message.js
https://github.com/cnodejs/nodeclub/issues/827
> API接口 /messages  message 结构暴露 create_at 字段

- api/v1/reply.js
- api/v1/topic.js
- api/v1/topic_collect.js
- api_router_v1.js
- middlewares/limit.js
- test/middlewares/limit.test.js
- web_router.js
> 修复API中的一些问题

- public/javascripts/main.js
- public/stylesheets/style.less
> 修复宽屏下footer没有固定在底部的Bug

- views/reply/reply.html
> 解决回复时间换行问题

- public/stylesheets/style.less
> 修正 <body> 无衬线体的 fallback

- public/stylesheets/style.less
> Fix text-decoration of the image of sponsor

- api/v1/topic.js
- test/api/v1/topic.test.js
- test/support/support.js
- views/static/api.html
> 主题详情api的评论列表中添加is_uped字段，用于标识特定用户是否对评论点赞

- controllers/user.js
https://github.com/cnodejs/nodeclub/issues/944
> 修改我的收藏列表分页问题

- public/libs/editor/ext.js
> fix修复图片、链接插入位置bug
